### ISSUE TITLE
Cannot open right click settings

### ISSUE THREAD

**Issue by jcau8** [GPUOpen-Tools/frame_latency_meter#5]
I think what is happening is that whenever I right click in command prompt it automatically copies (I am using windows 11 if that helps) and I can't seem to turn this feature off. If there is another way of opening the settings that would be really helpful because I can't use flm right now which is really annoying. Thanks!

**Comment by Corolix** [comment]
To access the settings with Right Click in Windows 11, you need to have the Default terminal app set to "Windows Console Host". The Windows Terminal doesn't seem to the detect the Right Clicks.

**Comment by jcau8** [comment]
Thank you very much I will try this later today, this is under dev settings in windows right?

**Comment by Corolix** [comment]
Lol, I was expecting you solved the issue by yourself, but I’ll help you out!

If you’re using the Windows Store Terminal, you can’t open the settings directly via right-click. To access them, you need the legacy terminal. Another way to open the legacy terminal is by running flm.exe as an administrator.

**Comment by jcau8** [comment]
Thank you! Your original message solved the problem.

**Comment by juansosa7766-hue** [comment]
//////nklñp0
